### ISSUE TITLE
Remove script tag mymr?

### ISSUE THREAD

**Issue by brawer** [silnrsi/font-padauk#5]
Padauk supports both the script tags `mymr` and `mym2`. However, according to  https://www.microsoft.com/typography/OpenTypeDev/myanmar/intro.htm#appendix: “The script tag for Myanmar script for use with the Myanmar shaping engine is mym2 and not mymr. The script tag mymr has limited support and should not be used.”

**Comment by mhosken** [comment]
Padauk is designed to work in as many contexts as possible including Windows XP. For backward compatibility, we include the mymr script tag, for systems that do not support the mym2 script. This presumes that including both mymr and mym2 causes no technical problems. In terms of size, mymr support is mostly a rehash of the DFLT script support, with the addition of language support (since DFLT isn't allowed to have languages due to a bug in the standard that people are reluctant to fix). So removing mymr from the font would save next to no space beyond the script,lang and feature tables. There are no extra lookups unique to mymr (AFAIK).

**Comment by brawer** [comment]
Thanks for the kind explanation!
